name: My First Concurreny Workflow

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building the code"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: echo "Testing the code"

  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: production-deployment
      cancel-in-progress: true
    needs: [build, test]
    
    steps:
      - name: sleep
        run: sleep 30  
      - name: Deploy
        run: echo "Deploying the code"
