name: My First ASCII Artwork

on:
  push:
    branches: main

jobs:
  cowsay:
    runs-on: ubuntu-latest

    steps:
    -  name: Checkout
       uses: actions/checkout@v4
    
    -  name: Run ACII Artwork
       run: |
          chmod +x generate-ascii-art.sh
          ./generate-ascii-art.sh