name: My First Multi-Job WorkFlow

on:
  push:
    branches: main

jobs:
    job1:
      runs-on: ubuntu-latest

      steps:
        -  name: Checkout
           uses: actions/checkout@v4

        -  name: Install Cowsay
           run: |
             sudo apt update
             sudo apt install cowsay -y
        -  name: Generate ASCII
           run: cowsay -f dragon "Run for cover, I am a DRAGON.... RAWR" >> dragon.txt

        -  name: Upload Dragon text file
           uses: actions/upload-artifact@v4
           with:
              name: dragon-text-file
              path: dragon.txt
    job2:
      needs: job1
      runs-on: ubuntu-latest
      steps:
        - name: Download Dragon text file
          uses: actions/download-artifact@v5
          with:
            name: dragon-text-file 

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt
    
    job3:
      runs-on: ubuntu-latest
      needs: [job2, job1]
      steps:
        -  name: Download Dragon text file
           uses: actions/download-artifact@v5
           with:
            name: dragon-text-file
            
        -  name: Display dragon
           run: cat dragon.txt
        
        -  name: Simulate Deployment
           run: echo "Deploying dragon.txt"