name: My First Workflow_dispath

on:
  workflow_dispatch: 
    inputs:
        logLevel:
            description: 'Log level'
            required: true
            default: 'warning'
            type: choice
            options: [info, warning, debug]
        tags:
            description: 'Test Scenario tags'
            required: false
            type: boolean
        environment:
            description: 'Environment to run tests'
            required: true


jobs:
  log-the-inputs:
    runs-on: ubuntu-latest

    steps:
      -  name: Display inputs
         env:
           LEVEL: ${{ inputs.logLevel }}
           TAGS: ${{ inputs.tags }}
           ENVIRONMENT: ${{ inputs.environment }}
         run: |
           echo "Log Level: $LEVEL"
           echo "Tags: $TAGS"
           echo "Environment: $ENVIRONMENT"
